### PR TITLE
Try to kick offline immediately'ish

### PR DESCRIPTION
**Pull request by SMTDDR**
My attempt at making gsProfileServer knock someone offline the moment they're banned. I think this works, but if anyone has a better idea ....go for it :)

### CODE REVIEW

**Comment by AdmiralCurtiss** [comment]
You might want to `return` out of that after closing the connection so it doesn't still try to perform whatever command.

**Comment by SMTDDR** [comment]
added

**Comment by ghost** [comment]
When the pull request will be pull to master ?

**Comment by kyle95wm** [comment]
They'll probably never do it. It took a few months for them to merge a simple commit I made

**Comment by AdmiralCurtiss** [comment]
Someone will merge it once they have the time and mood to test it.

**Comment by kyle95wm** [comment]
It has already been tested HOWEVER what I don't know yet is if the banned player will get kicked if they go on with another game. If this is the case, bans will have to be server-wide then or we can have ourselves a laugh while the hackers desperately try to connect to other games only to get kicked off :p

**Comment by kyle95wm** [comment]
@SMTDDR you might wanna close this because my PR has the same commit

**Comment by SMTDDR** [comment]
@kyle95wm .....if you say so boss
download

**Pull request closed without merging**
