### PR TITLE
Update gamestats.cfg

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by kyle95wm** [comment]
What will this fix?

**Comment by ghost** [comment]
I've just updated some text.
I also may do a new pull request soon to add some more salt # lines. I've also added pokemondpds' salt to this (and BeanJrFi)

**Comment by sepalani** [comment]
@PokeAcer549 
Could you add these two salts and rebase your commit into a single one, please?

```
msolympic - kyYszdUlxukYsLNpDHPJ
mschargedwii - DbfBialvJznkQWYuOrRa
```

For those having the missing games, it seems that the salt is located into the main.dol for most Wii games and I was able to find it using the following regexp:

```
([a-zA-Z]{20})([0-9a-fA-F]{32})
```

The first group is the salt, the second one a bunch of number right after the salt. Next to them you should find the game name.

Due to the lack of salts discovered I'm not sure for this regexp, so I've done another one more generic that might not only match the salt.

```
([a-zA-Z]{20})([0-9a-zA-Z]{32})
```

I used MadEdit as hex editor and the extracted main.dol from those games with the given regexp to find the salt.

**Comment by mm201** [comment]
These are useless without implementing what was actually on those servers, plus 3 missing RNG constants and an xor mask are required to decrypt requests.

https://github.com/mm201/pkmn-classic-framework/wiki/gamestats2-server#request-encryption

They should all be squashed together into a single string that looks like `HZEdGCzcGGLvguqUEKQN0001d93500002dd5000000082db842b2syachi2ds`.

**Comment by ghost** [comment]
@sepalani I've added the new keys.
@mm201 a lot of these servers only want random encrypted strings, you should know this.

**Comment by sepalani** [comment]
Does the pokemon salt was followed by those constants where it was found?

Like that:

```
DbfBialvJznkQWYuOrRa0002282500000ef90000020042db60ecmschargedwii
```

EDIT:
@PokeAcer549  thanks, could you rebase your commit into a single one, please?

**Comment by ghost** [comment]
If they are like that @sepalani I'll go find some more :P

**Comment by sepalani** [comment]
I didn't find it in AC:WW the only DS game I have. But I don't in what file I should search and if I had to decompress some LZ11 files before, so it won't help :v/.

**Comment by ghost** [comment]
I can't find PBR's key either :/

**Comment by mm201** [comment]
@PokeAcer549 All the servers I work with expect a specific formatted response. I know of the upload-only servers and how they're replayable but I have no idea what percentage of servers work this way.

(Decrypting the requests is still necessary to do anything with them like make leaderboards.)

The constants should be in the same string with the salt so there's no reason _not_ to include them--at least in a comment.

**Comment by ghost** [comment]
@mm201 but sometimes you can't find the key...

**Comment by sepalani** [comment]
I said it was working for Wii games not the DS ones since I wasn't able to find the one used in AC:WW. Unless some know how to find it in a DS game this regexp may not work. Plus most NDS games use compression algorithm such as LZ11 and others.

Concerning Wii games here there are (I added SSBB BTW):

```
mschargedwii 3 DbfBialvJznkQWYuOrRa # Mario Strikers Charged Football  # 0002282500000ef90000020042db60ecmschargedwii
msolympic 3 kyYszdUlxukYsLNpDHPJ # Mario & Sonic at the Olympic Games # 0003810500002d1f00020000173566ceMSolympicwii
smashbrosxwii 3 SeBQcoBRMEYxbDhcvtAQ # Super Smash Bros. Brawl  # 0001079d0000520f10000000069107d7smashbrosxwii
```

@PokeAcer549 can you add those, please?

**Comment by mm201** [comment]
AC:WW is a very old game and doesn't use any of the hashing/encrypting of later versions.

**Comment by sepalani** [comment]
Where/How was find the salt then?

**EDIT:**
I extracted the game with Tinke and try this regexp with all the files without any success. The same when I was looking for the salt directly through all the files. So either, it's compressed, archived, xor'd, etc. (or I wasn't searching in the write place)

**EDIT 2:**
I can't find the string acrossingds either. I suspect it to be in an overlay but I'm not sure.

**Comment by mm201** [comment]
You can probably find it in the same overlay containing the gamestats URLs. It is alone in this case.

**Comment by ghost** [comment]
Added even more keys in now XD
Thank god GitHub allows me to add it in.
Should I go through _all_ of my games to check?

EDIT: Pokemon Battle Revolution's key is definitely not in main.dol

**Comment by sepalani** [comment]
@PokeAcer549 
You should use git to rebase those commits btw, I don't think github has such a feature.

@mm201 
It seems that "http" was found in both rom.nds and overlay9_65 but as expected there are probably compressed because strings are truncated in a very strange way.

**Comment by ghost** [comment]
@sepalani it literally says:
'Add more commits by pushing to the patch-1 branch on PokeAcer549/dwc_network_server_emulator.'
And I've done so to the patch-1 branch and master branch.

**Comment by sepalani** [comment]
It would be clearer to add just a single commit for all of this. That's why I suggested you to use git rebase instead of stacking commit one by one, like github is suggesting you. These commits almost do nothing, they just edit a simple configuration file. Plus it will be clearer when it will be merged into the parent/master repository having just one commit for that.

**Comment by ghost** [comment]
I don't personally have git on my PC.
I'd rather do it like I am - when they do eventually accept it, it'll delete the branch after it's added all commits into one.
Also, we should start a lot more research - I can buy some more games for testing.

**Comment by mm201** [comment]
@sepalani You need `blz.exe`. https://gbatemp.net/threads/nintendo-ds-gba-compressors.313278/

**Comment by sepalani** [comment]
That's what I used, i'm looking for the string right now.

**Comment by ghost** [comment]
I get 'File size error' on all NDS roms I try..

**Comment by sepalani** [comment]
You've to use it on overlay you extracted from the ROM (using Tinke for example).

BTW, I'm glad these programs support wildcard because decompressing 148 overlays one by one would have been such a pain.

Anyway, I didn't find them in there, so I'm guessing there are the arm files and the rom.nds files which are left.

**Comment by ghost** [comment]
ooooh.
Getting DSBuff now.

**Comment by sepalani** [comment]
Okay, it was in the arm9.bin file. You've to decompress it if it's compressed. You can find the internal name and few strings before there is the salt without any parameter for AC:WW. It means the regexp is useless in this case =vP.

**Comment by ghost** [comment]
Oh good. I've been wanting to see what acrossingds checks for - can you put the string here?

**Comment by sepalani** [comment]
It's the same, so a bit useless:

```
gOAkBaBav5XHlGyUKOOD
```

Preceded by a format string:

```
%s?pid=%llu&region=%s
```

followed by some strings

```
%llu
pid
hash
data
region
acrossingds
h2P9x6
%s?pid=%llu&hash=%s&region=%s
```

separated by nul bytes of course.

**Comment by ghost** [comment]
So it sends the region and PID and hash and other things? So maybe it's another way of DLC - I already know about axing.nintendowifi.net but this is only on first connection, it will retry if it can't, but once it has, it will no longer connect, so we could make gamestats give us DLC.

**Comment by sepalani** [comment]
You can use a DS emulator to do so and then reset your save each time to test it.

BTW, mschargedwii is twice in the list.

**Comment by ghost** [comment]
Thanks for telling me :P

**Comment by sepalani** [comment]
You removed the wrong one =v/

**EDIT:**
Another reason to rebase your commit with git :vP

**Comment by ghost** [comment]
I don't really need the big string with it, now do I.

**Comment by sepalani** [comment]
Well the goal is to make a working GamestatsHTTP server, so having this string might help. You've to be coherent, either you put this string for each Wii game or you don't.

**Comment by ghost** [comment]
So you want me to go through each game to get that string, when AltWFC devs haven't even added it?

**Comment by sepalani** [comment]
It wasn't my intention. My intention was to make you decide or not to add those strings for the Wii games I added or not, not the whole file. Unless you've them all =vP. But as you see, some games don't have that string.

**Comment by ghost** [comment]
True. We need more strings for gamestats, definitely.
And I removed the extra line for smash.
I can say MSChargedWii gives a stat error - My GamestatsHTTP is for stuff like tetrisds mainly, which wants to have a random base64'd string.

**Comment by PokeAcer549** [comment]
@sepalani is your server you gave to Ciapa based on AltWFC's?

**Comment by sepalani** [comment]
Nope, it isn't. I write it from scratch based on the successful login on altwfc of Fortune Street and my old dumps. This server should be faster than altwfc because of the dummy responses. Plus altwfc needs its database to have the gamestats server working. Mine also support Python3.

**Comment by PokeAcer549** [comment]
Oh nice.
What games does it work with, and does yours have it's own DB?

**Comment by sepalani** [comment]
**It's off-topic to discuss of it here. You should ask me with a PM or something else than asking it in a PR, even if it's yours technically.**

To answer your question (again), as I said before it uses dummy responses, so no db, no dependencies like twisted or so. But, it can automatically detects specific files to load them as dummy data for the responses if present. FYI, it was mainly designed for Fortune Street as stated before in Wiimmfi forums.

**Comment by PokeAcer549** [comment]
Noted, check your PM on WHB, delete all messages unrelated.

**Comment by polaris-** [comment]
Just want to point out that the changes to the comments in 28b8137cd3f251b7fea19586a8608c8903c3bca7 aren't really necessary I think. I could've swore I had code in the GamestatsHTTP server that actually made the defaults, but I guess not, though.

At any rate, I don't see anything really wrong with this pull request so I'm merging it.

**Comment by ghost** [comment]
OK :P

**Pull request merged**
