### PR TITLE
Resolved error with pending buddy messages

### PR DESCRIPTION
**Pull request by barronwaffles**
Attempting to pass mutable type was throwing exception - prevented accounts from logging in

### CODE REVIEW

**Comment by sepalani** [comment]
Do you have the traceback for this? I'd like to investigate the issue. Otherwise, this change SGTM.

**Comment by barronwaffles** [comment]
I don't think the log archive for it still exists, sorry.
I'll see if I can recreate it next week.

**Comment by barronwaffles** [comment]
@sepalani - I didn't have any luck forcing a situation where get_pending_messages was called, but using transport.write with a mutable type in a test script threw the exception I saw in the past.

**Comment by sepalani** [comment]
Ping @polaris- 

This PR seems to make sense. Moreover, the code base is using mostly everywhere:
```python
self.transport.write(bytes(msg))
```
Whereas, the code modified by this PR is the only exception. Was there any reason to use bytearray instead of bytes?
https://github.com/polaris-/dwc_network_server_emulator/commit/0a0e37cc113e91d5b8482d6395488445221c8370#diff-77b9e52cb762af8d73504b4e1824ab57R583

**Comment by polaris-** [comment]
@sepalani Not that I remember. I'll merge this then. Thanks for checking into it.

**Pull request merged**
