### PR TITLE
Add new identifiers to admin page for later banning

### PR DESCRIPTION
**Pull request by kyle95wm**
This is only half of what needs to be done

### CODE REVIEW

**Comment by SMTDDR** [comment]
@kyle95wm  Got your IRC message. Is something in this PR not working the way you want?

**Comment by kyle95wm** [comment]
Yeah for some reason the server just hangs whenever I add the new identifiers but maybe its because either my sql statement isn't correct (i added on to what you had with the whole "and" thing) or my parsed auth tokens aren't correct

**Comment by kyle95wm** [comment]
@AdmiralCurtiss which duplicate lines might I ask?

**Comment by AdmiralCurtiss** [comment]
All those "&lt;input type='hidden' name='[name]' value='"+[var]+"'&gt;" ones that are there twice.

**Comment by kyle95wm** [comment]
You mean to tell me they're still there or did I fix them?

**Comment by kyle95wm** [comment]
It's been decided that we will work on banning by game ID and IP address

**Comment by SMTDDR** [comment]
Yeah, first we're gonna change this line of code: https://github.com/polaris-/dwc_network_server_emulator/blob/master/gamespy/gs_database.py#L125   to something like, <code>CREATE TABLE IF NOT EXISTS whitelist (userid TEXT, gameid TEXT, macadr TEXT, ipaddr TEXT)</code>   

Then after this line: https://github.com/polaris-/dwc_network_server_emulator/blob/master/nas_server.py#L88  we'll do something like <code>post['ipaddr'] = self.client_address[0]</code>

Then around here: https://github.com/polaris-/dwc_network_server_emulator/blob/master/nas_server.py#L102  and https://github.com/polaris-/dwc_network_server_emulator/blob/master/nas_server.py#L112 ...check if they're banned probably.

Then more stuff... I'll see if I can't get something going before monday on my repo-fork.

**Comment by kyle95wm** [comment]
Keep me updated on the situation. Looking forward to finally having a stronger ban system that no average person can bypass

**Comment by kyle95wm** [comment]
Okay I just tested and theres a slight problem with my setup. My IP reads "127.0.0.1" so it won't really work

**Comment by kyle95wm** [comment]
Had to change my server over to port 80 for the time being to allow it to read client IP's. Polaris recommended I run a web server with the server to "make all the servers work" by removing the comment line on the loop back and commenting the line above (the one you use)

**Comment by SMTDDR** [comment]
Oh wait... actually, banning by IP and gameid is specific enough that we don't need a whitelist anymore.  The table will instead be called <code>banned</code> and anyone in that table can't login in; simple & straight-forward.

**Comment by kyle95wm** [comment]
Sounds good

**Comment by kyle95wm** [comment]
sadly we’re gonna have to put IP banning on hold for a while until we can figure this whole thing out.
for SOME reason Mario Kart Wii wants to use the storage server which makes friend adding work. This means Apache is required for it to work which means nas has to be on port 9000. HOWEVER the IP that is grabbed from nas on port 9000 is 127.0.0.1 and thats for all players. We need to make it so that the public IP is shown even if nas is not on port 80

**Comment by mm201** [comment]
`mod_proxy` should stuff the original IP into the `X-Forwarded-For` request header.

**Comment by kyle95wm** [comment]
Mind explaining that to me? I don't quite understand

**Pull request closed without merging**
