### PR TITLE
Made a script to easily install and uninstall the server on a fresh Linux box

### PR DESCRIPTION
**Pull request by kyle95wm**
I realize the scripting is very primitive here, but I've tested this and it get's the job done! Feel free to contribute changes

### CODE REVIEW

**Comment by kyle95wm** [comment]
@HeikkiNiemela Will do!

**Comment by kyle95wm** [comment]
so is someone going to merge this or no?

**Comment by kyle95wm** [comment]
Added uninstall script. Please test

**Comment by kyle95wm** [comment]
Okay I just re-ran the install script on a fresh Ubuntu and I'm already seeing problems. Looks like the script isn't outputting the sites-available config files to the directories properly maybe someone can look into this. Also Im getting several errors about modules not being enabled. The uninstall script does need a bit more work as well since it encountered 2 errors towards the end

**Comment by polaris-** [comment]
How is this working now? What environments has it been tested in? Has anyone used it and can give any feedback? I don't have a system to test it out with and don't know enough shell scripting to comment.

**Comment by kyle95wm** [comment]
I believe this works with Ubuntu (and other similar OS's) I tried testing it but of course I already have a Wamp server running which gives error 23404 (but I'm assuming the script works)

**Comment by mm201** [comment]
Remind me sometime to make a powershell script for WIMP stacks.

**Comment by kyle95wm** [comment]
Theres no point in keeping this open

**Comment by kyle95wm** [comment]
It's amazing nearly 4 months later and the script has come a really long way. It is nearly 500 lines long

**Pull request closed without merging**
