### PR TITLE
General Improvement

### PR DESCRIPTION
**Pull request by sepalani**
Summary:
- Upgraded solution to **Visual Studio 2015**
- Most files are **PEP8 compliant**
- **Truth Value Testing** used when safe, faster than comparisons
- **Improved logger**, when custom logger are used we can pass as many parameter we want just like the one from the logging module
- **Comprehension lists** used when possible
- **Docstring added**, automatically recognized by python and used to make helps, docs, etc.
- Added a **dwc_config module** for more flexibility
- **Updated README.md** because I considered that dependencies must be here just like it was before. Useful when you want to make it works for other platforms (like Windows or another OS from a clean install)

In sum, servers are slightly faster to process requests/tasks because of those functions/methods improvements _(usually 1/3~1/4 faster according to **timeit module**)_. You can also use the **altwfc.cfg** file to customize servers' IP & port. Otherwise, it should work the same just like before.

**EDIT:**
By the way, I recently fixed the **Error Code 24101**

### CODE REVIEW

**Comment by kyle95wm** [comment]
Woah this is crazy :p

There's been a lot of changes ever since I sent my PR's and my server code has changed a lot ever since. Wish me luck in implementing this onto BeanJrFi

**Comment by WinterPhoenix** [comment]
Woah cool beans.

**Comment by kyle95wm** [comment]
Is there an easy way to implement most of this stuff? Do I need to install any new packages besides Apache, Python 2, Twisted and DNSMASQ? I need to know so I can update my install script

**Comment by sepalani** [comment]
Short answer: git merge

There is no new dependencies and the only new files are from the config module. Some files should be merged automatically without conflict. For the rest, you should check the difference and merge them manually.

Otherwise, if want to be extremely careful you can cherry pick each commit you want one by one.

**Comment by AdmiralCurtiss** [comment]
Haven't looked at the details yet but all of this sounds good, thanks a lot!

**Comment by sepalani** [comment]
I fixed the Error Code: 24101. Its seems to work on Boom Street and Monster Hunter Tri. Hopefully most Wii games shouldn't have this error anymore.

**Comment by sepalani** [comment]
Weird behaviors happen when a Wii and Dolphin with the same NAND connect to the same game. Instead of kicking one of them it crashes and the game falls into an infinite loop.

```
Unknown exception: Traceback (most recent call last):
  File "S:\Projects\dwc_network_server_emulator\gamespy_gamestats_server.py", line 185, in rawDataReceived
    cmds.get(data_parsed['__cmd__'], cmd_err)(data_parsed)
  File "S:\Projects\dwc_network_server_emulator\gamespy_gamestats_server.py", line 222, in perform_authp
    self.db)
  File "S:\Projects\dwc_network_server_emulator\gamespy\gs_utility.py", line 130, in login_profile_via_parsed_authtoken
    userid = authtoken_parsed['userid']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by polaris-** [comment]
@sepalani Is that weird behavior you mentioned because of the changes in this pull request or was it in the code originally?

**Comment by sepalani** [comment]
@polaris- 
It was in the code originally when calling **login_profile_via_parsed_authtoken** and passing None as parameter. Obviously `userid = authtoken_parsed['userid']` will fail. It was None because `authtoken_parsed = gs_utils.parse_authtoken(data_parsed['authtoken'], self.db)` might fail and wasn't checked. However because **profile_id** when deconstructing the tuple is checked, we can return a tuple of None which fixes the issue.

**Comment by polaris-** [comment]
@sepalani Oh, I see. Do you think you could submit a patch for that and also resolve the conflicts? (I think the conflicts started when I merged BeanJr's pull request... sorry.)
If so, then I will accept the pull request. Also, sorry for being late to respond to this. I appreciate you putting time into making the server better. If you have any plans on making more big changes to the code, let me know and I could possibly set you up as a contributor if everything sounds good.

**Comment by kyle95wm** [comment]
Yeah sorry about that. In fact I still have a PR waiting to be merged with an updated ban system, but not that it matters anyways

**Comment by sepalani** [comment]
@kyle95wm 
Don't worry, I'll just have to rebase my commits (and maybe resolve conflicts), so it's no big deal. By the way, you also have conflicts in your PR.

@polaris- 
In fact, I've already patched this issue in my last commit.

I'll probably fix conflicts this week-end and adding @kyle95wm stuff in the config file.

**Comment by kyle95wm** [comment]
I'm just curious, will we really see a significant speed boost? Is it really worth it for me to put countless hours of comparing/modifying my code to fit this new system? What are the real benefits here?

**Comment by AdmiralCurtiss** [comment]
https://help.github.com/articles/configuring-a-remote-for-a-fork/
https://help.github.com/articles/syncing-a-fork/
http://git-scm.com/book/en/v2/Git-Branching-Rebasing

Please learn how to use git.

**Comment by sepalani** [comment]
@kyle95wm 
Don't forget that it fixes issues and adds a configuration file. I personally don't think it has a significant speed boost, it improves methods here and there by increasing slightly their speed. So I guess you can handle clients faster than before, even though players might not see it. Plus, most files are PEP8 compliant now (and 80 columns max) allowing people to work on it with non graphical environment via a Terminal or a TTY.

**Comment by sepalani** [comment]
PR rebased, ready to be reviewed.

@kyle95wm
You should check if I did not break anything that you've done. I alse added your **RegPageServer** into **master_server.py**. Please, avoid the use of useless spaces or parentheses, especially for crafting strings. And do not import module that you do not use. I advise you to check the [PEP8 norm](https://www.python.org/dev/peps/pep-0008/) to produce a cleaner and more pythonic code.

I added an extra commit compared to the older PR, it moves loggers in the configuration file. Now, you can use an alternative configuration file if wanted. Then, I've done some minor code cleanups.

**Comment by polaris-** [comment]
Thanks for rebasing it. I gave the new changes a look over and it looks fine, I think. I also like the change to loggers being in the config file. :+1:

**Pull request merged**
