### PR TITLE
Console ban + Kick banned players from the server if their IP is in the IP bans list

### PR DESCRIPTION
**Pull request by kyle95wm**
I've added a 2nd banning method to only ban consoles from connecting to the server based on their MAC address. This was originally requested by Starlight, so that banning Nintendo DS consoles would be stronger because MAC changing on a DS is (from what I'm told) next to impossible

Please see commit comments for full details

NOTE: I did 90% of the work - copied and pasted code and modified it and got help from SMTDDR on a few things. I feel pretty good about myself right about now

NOTE: Kicking players from the server only work on IP based bans and not console bans

### CODE REVIEW

**Comment by kyle95wm** [comment]
This just about completes the ban system for the time being....

**Comment by kyle95wm** [comment]
Okay theres a little bit of a problem with the latest commit. Whenever a DS connects this shows up in the console

[2015-05-29 01:48:37 | NasServer] Unknown exception: Traceback (most recent call last):
  File "/home/pi/dwc_network_server_emulator/nas_server.py", line 147, in do_POST
    elif self.server.db.is_console_cfc_banned(post):
  File "/home/pi/dwc_network_server_emulator/gamespy/gs_database.py", line 419, in is_console_cfc_banned
    row = tx.queryone("SELECT COUNT(*) FROM console_cfc_banned WHERE cfc = ?",(postdata['cfc'],))
KeyError: 'cfc'

I assume CSNUM also has this problem too. I did not anticipate this when coding that DS's don't have CSNUM or CFC

**Comment by kyle95wm** [comment]
new parameters will be re-activated once there's a fix

It won't be that hard to re-activate them as they're just commented out.

**Comment by AdmiralCurtiss** [comment]
Also, that "now we wait....." comment in the other discussion does not exactly encourage us to merge this quickly -- quite the opposite, in fact. And you can see for yourself why stuff is not merged immediately and needs testing, as you somehow managed to completely break DS connectivity with those few additional lines without noticing.

**Comment by kyle95wm** [comment]
Thanks I'll look into this

Sorry if I was sounding impatient on the discussion thread idk what i was thinking

**Comment by kyle95wm** [comment]
@AdmiralCurtiss just so Im understanding correctly,  this is going in NAS server?

**Comment by AdmiralCurtiss** [comment]
I'd put it in the `is_console_*_banned` functions and just return a default `False` if there's no relevant data to check.

**Comment by kyle95wm** [comment]
so gs_database then?

**Comment by kyle95wm** [comment]
is https://github.com/kyle95wm/dwc_network_server_emulator/commit/b129bcd5c425247daca24d9dbd3b7ba97dadc1e5 the correct way?

I tried making sense of the documentation but I just can't get it

**Comment by kyle95wm** [comment]
I tested with Desemue on Mario Kart DS and it connects perfectly fine without errors. Down the road I might add bssid/apinfo as a parameter to ban if one so desired now that I'm aware of the post data check you provided me with as a starting point

Before this is merged, I advise this be tested further. One can git clone the main repo (or mine doesn't matter) and if the main repo is cloned, cherry pick my commit and test with a real DS console

Once we can confirm this is safe for production, it can be merged. Note that the "banned" table is now obsolete and separate database tables are being used for each parameter (a lazy way of making the server check against all the parameters by querying the tables one by one.

@SMTDDR said that this is bad database design, but atm we're just "shoving in features" we can worry about cleanup later.

**Comment by kyle95wm** [comment]
I've now made it so IP bans are server-wide and not game specific.

For any existing ban tables please either remove them to allow the master to re-create them, or remove the game ID row manually via sql lite

**Comment by kyle95wm** [comment]
I think this PR is ready to be merged, as I've done everything I can possibly think of. @AdmiralCurtiss feel free to review my code and make any needed changes.

**Comment by kyle95wm** [comment]
re-opening PR under different branch.....

**Pull request closed without merging**
