### PR TITLE
Changed error codes

### PR DESCRIPTION
**Pull request by kyle95wm**
I changed the "login denied" from 23914 to 23917

### CODE REVIEW

**Comment by ghost** [comment]
AltWfc should copy the official WFC before shutdown, not Wiimmfi.

For other error code you can continue : 
20103 : Console creation denied
20104 : Profile banned
etc...

**Comment by kyle95wm** [comment]
Profile banned was actually removed a few commits back by @AdmiralCurtiss since we "don't need it" anymore but fortunately I still have a copy of the code on my server

**Comment by kyle95wm** [comment]
I think ill push another commit commenting where the error codes are and how to change them so that if anyone wants to set up their own error codes they can

**Comment by ghost** [comment]
The error code for Console creation should be 20103, can you change the pull request ?

**Comment by ghost** [comment]
When the pull request will be pull to master ?

**Pull request closed without merging**
