### PR TITLE
Fix get_next_userid for null value returned by sql

### PR DESCRIPTION
**Pull request by SMTDDR**

### CODE REVIEW

**Comment by SMTDDR** [comment]
This should fix the issue discussed here: https://github.com/polaris-/dwc_network_server_emulator/issues/81#issuecomment-76525330

**Comment by kyle95wm** [comment]
is this really needed? Ive started my server from SCRATCH without issues

**Comment by SMTDDR** [comment]
shrug  ....I don't understand how that error occurred either.

**Comment by SMTDDR** [comment]
Actually, I am gonna close this if you were able to start your server from scratch and acctcreate worked.

**Pull request closed without merging**
